<a href="https://colab.research.google.com/github/Alton1998/Scoliosis/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# imports
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [2]:
X_train_class = []
X_test_class = []
X_val_class = []
y_train_class = []
y_test_class = []
y_val_class = []
with open("X_train_class.pkl","rb") as f1, open("X_test_class.pkl","rb") as f2, open("X_val_class.pkl","rb") as f3, open("y_train_class.pkl","rb") as f4, open("y_test_class.pkl","rb") as f5, open("y_val_class.pkl","rb") as f6:
  X_train_class = pickle.load(f1)
  X_test_class = pickle.load(f2)
  X_val_class = pickle.load(f3)
  y_train_class = pickle.load(f4)
  y_test_class = pickle.load(f5)
  y_val_class = pickle.load(f6)

In [3]:
X_train_class = X_train_class.values
X_test_class = X_test_class.values
X_val_class = X_val_class.values
y_train_class = y_train_class.values
y_test_class = y_test_class.values
y_val_class = y_val_class.values

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
scaler = StandardScaler()

In [6]:
# Scaling the data based on training
X_train_class = scaler.fit_transform(X_train_class)
X_test_class = scaler.transform(X_test_class)
X_val_class = scaler.transform(X_val_class)

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
lr=LogisticRegression()

In [9]:
lr.fit(X_train_class,y_train_class)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [10]:
y_val_pred = lr.predict(X_val_class)

In [15]:
y_val_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [11]:
from sklearn.metrics import confusion_matrix,classification_report

In [13]:
print(confusion_matrix(y_val_class,y_val_pred))

[[0 5]
 [0 8]]


In [14]:
print(classification_report(y_val_class,y_val_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.62      1.00      0.76         8

    accuracy                           0.62        13
   macro avg       0.31      0.50      0.38        13
weighted avg       0.38      0.62      0.47        13



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
y_test_pred = lr.predict(X_test_class)

In [18]:
print(confusion_matrix(y_test_class,y_test_pred))

[[ 1  7]
 [ 4 41]]


In [19]:
print(classification_report(y_test_class,y_test_pred))

              precision    recall  f1-score   support

           0       0.20      0.12      0.15         8
           1       0.85      0.91      0.88        45

    accuracy                           0.79        53
   macro avg       0.53      0.52      0.52        53
weighted avg       0.76      0.79      0.77        53

